# Generated by Django 3.1 on 2020-09-14 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregprice',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'InActive'), ('ACTIVE', 'Active')], default='INACTIVE', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='rank_status',
            field=models.CharField(choices=[('UNDEFINED', 'Undefined'), ('PREMIUM', 'Premium'), ('PLATINUM', 'Platinum'), ('ULTIMATE', 'Ultimate'), ('PRO_ULTIMATE', 'Pro_ultimate'), ('PRO_BASIC', 'Pro_basic'), ('BASIC', 'Basic')], default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('DEACTIVATED', 'Deactivated')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='companypricingplan',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Monthly'), (1, 'Yearly')], default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyregistrationpayment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('UNPAID', 'Unpaid'), ('CANCELED', 'Canceled'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='UNPAYED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyregprice',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'InActive'), ('ACTIVE', 'Active')], default='INACTIVE', max_length=200),
        ),
        migrations.AlterField(
            model_name='companystatuspayment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('UNPAID', 'Unpaid'), ('CANCELED', 'Canceled'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='UNPAYED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactuscompany',
            name='status',
            field=models.CharField(blank=True, choices=[('TRASH', 'Trash'), ('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactusemployee',
            name='status',
            field=models.CharField(blank=True, choices=[('TRASH', 'Trash'), ('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactushome',
            name='status',
            field=models.CharField(blank=True, choices=[('TRASH', 'Trash'), ('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pay_status',
            field=models.CharField(choices=[('UNPAID', 'UnPaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank_status',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('ULTIMATE', 'Ultimate'), ('PREMIUM', 'Premium')], default='BASIC', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('DEACTIVATED', 'Deactivated')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('UNPAID', 'Unpaid'), ('CANCELED', 'Canceled'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='UNPAYED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 14, 57, 7, 538162)),
        ),
        migrations.AlterField(
            model_name='message',
            name='label',
            field=models.CharField(choices=[('WORK', 'Work'), ('MISC', 'Misc'), ('PRODUCT', 'Product'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='readstatus',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=200),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('TRASH', 'Trash'), ('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=100),
        ),
    ]
