# Generated by Django 3.1 on 2020-09-15 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0002_auto_20200914_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rank_status',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('PRO_ULTIMATE', 'Pro_ultimate'), ('PRO_BASIC', 'Pro_basic'), ('UNDEFINED', 'Undefined'), ('PLATINUM', 'Platinum'), ('ULTIMATE', 'Ultimate')], default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('DEACTIVATED', 'Deactivated'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyregistrationpayment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('CANCELED', 'Canceled'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='UNPAYED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyshortlistcustomers',
            name='payment_status',
            field=models.CharField(choices=[('SHORTLISTED', 'Shortlisted'), ('UNSHORTLISTED', 'Unshortlisted')], default='SHORTLISTED', max_length=200),
        ),
        migrations.AlterField(
            model_name='companystatuspayment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('CANCELED', 'Canceled'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='UNPAYED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pay_status',
            field=models.CharField(choices=[('PARTIAL', 'Partial'), ('UNPAID', 'UnPaid'), ('PAID', 'Paid')], default='UNPAID', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank_status',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('BASIC', 'Basic'), ('ULTIMATE', 'Ultimate')], default='BASIC', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('CANCELED', 'Canceled'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='UNPAYED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 21, 19, 48, 85168)),
        ),
        migrations.AlterField(
            model_name='message',
            name='label',
            field=models.CharField(choices=[('UNDEFINED', 'Undefined'), ('MISC', 'Misc'), ('PRODUCT', 'Product'), ('WORK', 'Work')], default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='msgstatus',
            name='delstar',
            field=models.CharField(choices=[('DELETE', 'Delete'), ('STARRED', 'Starred'), ('NORMAL', 'Normal')], default='NORMAL', max_length=200),
        ),
    ]
